/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
}
export interface CategoryUpdate {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
}
export type ExternalBlob = Uint8Array;
export interface Inquiry {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface Product {
  'id' : bigint,
  'moq' : bigint,
  'categoryId' : bigint,
  'name' : string,
  'imageUrl' : string,
  'rating' : number,
  'priceUSD' : number,
}
export interface ProductUpdate {
  'id' : bigint,
  'moq' : bigint,
  'categoryId' : bigint,
  'name' : string,
  'imageUrl' : string,
  'rating' : number,
  'priceUSD' : number,
}
export interface StoreInfo {
  'businessHours' : string,
  'city' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface SubmittedInquiry {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[CategoryUpdate], undefined>,
  'addProduct' : ActorMethod<[ProductUpdate], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllInquiries' : ActorMethod<[], Array<SubmittedInquiry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getInquiry' : ActorMethod<[bigint], Inquiry>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[bigint], Array<Product>>,
  'getStoreInfo' : ActorMethod<[], StoreInfo>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<
    [string, number, number, number],
    Array<Product>
  >,
  'submitInquiry' : ActorMethod<[string, string, string], bigint>,
  'updateCategory' : ActorMethod<[CategoryUpdate], undefined>,
  'updateProduct' : ActorMethod<[ProductUpdate], undefined>,
  'updateStoreInfo' : ActorMethod<[StoreInfo], undefined>,
  'uploadImage' : ActorMethod<[string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];